### ISSUE TITLE
Discrepancy between fmt verbs for fmt.Sprintf and Decimal.Append()

### ISSUE THREAD

**Issue by donovanhide** [woodsbury/decimal128#10]
Hopefully the example is clear, but for a zero decimal place precision format string, Append() seems to complain:

https://go.dev/play/p/rI9N5sFKwzn

I presume that the reason is that this line is not invoked by the previous early returns above it:

https://github.com/woodsbury/decimal128/blob/main/format.go#L839

**Comment by woodsbury** [comment]
Hey, thanks for raising this.

It looks like the parsing of the format string that Append() uses doesn't allow leading zeros in the precision whereas the standard library does. I've just pushed a commit changing it to make it match.

I'm planning on tagging a new release soon and that should include this change.

In the meantime, if you want to format a number with a precision of zero you can alternatively not specify any digits after the `.` - for example `.f` would format the decimal with a precision of zero. This should work both with the fmt package functions and Append().
