### ISSUE TITLE
Comparison with DEC64 format?

### ISSUE THREAD

**Issue by elimisteve** [woodsbury/decimal128#7]
DEC64 was invented by Douglas Crockford (of JSON and "JavaScript: The Good Parts" fame) a few years ago: https://www.crockford.com/dec64.html

I would love a comparison between DEC64 and decimal128!

The beginnings of a comparison, in which Doug says DEC64 is way simpler than what the IEEE came up with for decimal128: https://github.com/douglascrockford/DEC64/issues/29

Thoughts? Thanks!

**Comment by woodsbury** [comment]
Hi!

One thing to understand about the IEEE format for decimal floating point values is there's actually two of them.

The first format is the "densely packed decimal" format. This is the one Douglas seems to be referring to in that issue you linked, where 10 bits each are used to encode three decimal digits of the significand. It originated from IBM and can be a more difficult format to work with (though there are some scenarios where it can actually be helpful). This library **does not** implement that format.

The second format is the "binary integer significand" format. In this format the significand is encoded as a regular binary integer. This is the format that this library implements. You can read a little bit about it here: [decimal128 floating-point format](https://en.wikipedia.org/wiki/Decimal128_floating-point_format#Binary_integer_significand_field)

Looking at the DEC64 library, it appears like it also uses a binary integer to hold its significand, so it would seem that these two formats work pretty similarly (though the actual bit encoding is different).

In terms of other differences, comparing DEC64 to the IEEE decimal64, it looks like DEC64 gives you a little bit of extra precision in your significand at the expense of a little less range in your exponent - so DEC64 can't represent numbers as big or small, but could give you more digits of precision. The decimal128 format this library implements has bigger range and precision than both of them (at the expense of taking up twice as much space).

Hopefully that answers your question, let me know if there's anything else you'd like me to touch on.

**Comment by elimisteve** [comment]
This is helpful, thanks.

**Comment by elimisteve** [comment]
I wish decimal128 were simpler, but it's not too too complex and has all the other properties (lots of precision, can represent huge and tiny numbers, 0.1 + 0.2 == 0.3 (imagine that!), and more) I'm looking for for the programming language I'm just starting to implement.

Oh yeah: does decimal128 have overflow protection?

**Comment by elimisteve** [comment]
Apparently it does, yay: https://chat.openai.com/share/f0931a5a-649c-4e97-8a2f-287f4a363f4e
